$ErrorActionPreference = "Stop"

$token = $env:GITHUB_PERSONAL_ACCESS_TOKEN
if (-not $token) {
    Write-Error "GITHUB_PERSONAL_ACCESS_TOKEN environment variable is not set!"
}

$owner = "AigisYangyan"
$repo = "Persona_Notebook"
$tag = "release-2026-06-14"
$releaseName = "Personal Growth RPG Notebook release-2026-06-14"
$releaseBody = @"
Automated GitHub release generated by GitHub Actions.

Included assets:
- NSIS Windows installer
- MSI Windows installer
"@

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$rootDir = Split-Path -Parent $scriptDir

$exePath = Join-Path $rootDir "src-tauri\target\release\bundle\nsis\Personal Growth RPG Notebook_0.2.0_x64-setup.exe"
$msiPath = Join-Path $rootDir "src-tauri\target\release\bundle\msi\Personal Growth RPG Notebook_0.2.0_x64_en-US.msi"

if (-not (Test-Path $exePath)) {
    Write-Error "Could not find EXE installer at: $exePath"
}
if (-not (Test-Path $msiPath)) {
    Write-Error "Could not find MSI installer at: $msiPath"
}

$headers = @{
    "Authorization" = "Bearer $token"
    "Accept"        = "application/vnd.github+json"
}

Write-Host "Checking if release for tag '$tag' already exists..."
$release = $null
try {
    $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$owner/$repo/releases/tags/$tag" -Headers $headers -Method Get
    Write-Host "Release already exists. ID: $($release.id)"
} catch {
    Write-Host "Release does not exist. Creating new release..."
}

if ($null -eq $release) {
    $bodyJson = @{
        tag_name         = $tag
        target_commitish = "main"
        name             = $releaseName
        body             = $releaseBody
        draft            = $false
        prerelease       = $false
    } | ConvertTo-Json

    $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$owner/$repo/releases" -Headers $headers -Method Post -Body $bodyJson -ContentType "application/json"
    Write-Host "Successfully created release! ID: $($release.id)"
}

# The upload URL template looks like: https://uploads.github.com/repos/owner/repo/releases/id/assets{?name,label}
# We need to strip the placeholder from the end
$uploadUrlBase = $release.upload_url -replace '\{\?name,label\}', ''

function Upload-Asset {
    param(
        [string]$filePath,
        [string]$targetName
    )

    # Replace spaces with dots to match the previous naming convention
    $cleanName = $targetName -replace ' ', '.'

    # Check if asset already exists in the release
    Write-Host "Checking if asset '$cleanName' already exists in the release..."
    if ($release.assets) {
        $existingAsset = $release.assets | Where-Object { $_.name -eq $cleanName }
        if ($existingAsset) {
            Write-Host "Asset '$cleanName' already exists (ID: $($existingAsset.id)). Deleting it first..."
            Invoke-RestMethod -Uri "https://api.github.com/repos/$owner/$repo/releases/assets/$($existingAsset.id)" -Headers $headers -Method Delete
            Write-Host "Deleted existing asset '$cleanName'."
        }
    }

    Write-Host "Reading file: $filePath"
    $fileBytes = [System.IO.File]::ReadAllBytes($filePath)

    $uploadUrl = "$uploadUrlBase`?name=$cleanName"
    Write-Host "Uploading to: $uploadUrl"
    
    $uploadHeaders = $headers.Clone()
    $uploadHeaders.Add("Content-Type", "application/octet-stream")

    $uploadResponse = Invoke-RestMethod -Uri $uploadUrl -Headers $uploadHeaders -Method Post -Body $fileBytes
    Write-Host "Successfully uploaded '$cleanName'! Asset ID: $($uploadResponse.id)"
}

Upload-Asset -filePath $exePath -targetName "Personal Growth RPG Notebook_0.2.0_x64-setup.exe"
Upload-Asset -filePath $msiPath -targetName "Personal Growth RPG Notebook_0.2.0_x64_en-US.msi"

Write-Host "All assets successfully published to release '$tag'!"
